# Generated by Django 2.1.4 on 2019-01-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_two_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='usr_email',
            field=models.EmailField(max_length=264, unique=True),
        ),
    ]
